name: Rust

on:
  push:
    branches:
      - recursive
      - iterative
  pull_request:
    branches:
      - recursive
      - iterative

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm,
          macos-latest, macos-14, macos-15, macos-26, macos-13, macos-15-intel,
          windows-latest, windows-2025, windows-2022, windows-11-arm,
        ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests in release profile
      run: cargo test --release --verbose
